# Generated by Django 6.0.3 on 2026-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('patient', 'Patient'), ('clinician', 'Clinician')], default='patient', max_length=10),
        ),
    ]
